# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bdad37227b0dec7651593442804c746f4f6f98d2c881b77769eca7b1bc63f9907c7b345fcc002cce5cfbadeb772a18338f5c474a325f6db93b3ad854fe45bf2

test:
  secret_key_base: 9a14ceeced743cb1eb6f3d73cc157dc54596a211fbc86a7e49bf1fe0371aceb6b086af8e31e014e3762899807c363b3104dc5c65311570c6041557f14a5e2076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
